---
abstract: 'Micro Objects. Mo is less.'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  Test::More: '0.96'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mo
no_index:
  directory:
    - t
    - xt
    - inc
    - src
  package:
    - DB
recommends:
  Class::XSAccessor: '0'
  IO::All: '0'
  Moose: '0'
  Mouse: '0'
requires:
  perl: v5.6.0
resources:
  bugtracker: https://github.com/ingydotnet/mo-pm/issues
  homepage: https://github.com/ingydotnet/mo-pm
  repository: https://github.com/ingydotnet/mo-pm.git
version: '0.39'
x_Dist_Zilla:
  perl:
    version: '5.018001'
  plugins:
    -
      class: Dist::Zilla::Plugin::Run::BeforeBuild
      config:
        Dist::Zilla::Plugin::Run::Role::Runner:
          run:
            - 'touch src/**/*'
            - 'make -C src/ version all'
      name: Run::BeforeBuild
      version: '0.023'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: Git::Check
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      config:
        Dist::Zilla::Plugin::Git::GatherDir:
          include_untracked: '0'
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@INGY/Git::GatherDir'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@INGY/CheckPrereqsIndexed'
      version: '0.012'
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: '@INGY/CheckExtraTests'
      version: '0.022'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@INGY/@Filter/PruneCruft'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@INGY/@Filter/ManifestSkip'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@INGY/@Filter/MetaYAML'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::License
      name: '@INGY/@Filter/License'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@INGY/@Filter/Readme'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@INGY/@Filter/ExecDir'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@INGY/@Filter/ShareDir'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@INGY/@Filter/MakeMaker'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@INGY/@Filter/Manifest'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@INGY/@Filter/TestRelease'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@INGY/@Filter/ConfirmRelease'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@INGY/@Filter/UploadToCPAN'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@INGY/AutoPrereqs'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      config:
        Dist::Zilla::Plugin::Git::NextVersion:
          first_version: '0.001'
          version_by_branch: '0'
          version_regexp: (?^:^([0-9]+\.[0-9]+(?:\.[0-9]+)?)$)
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@INGY/Git::NextVersion'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@INGY/ReadmeFromPod'
      version: '0.21'
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@INGY/PkgVersion'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@INGY/MetaConfig'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@INGY/MetaJSON'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@INGY/NextRelease'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@INGY/PodSyntaxTests'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          bail_out_on_fail: '0'
          fail_on_warning: author
          fake_home: '1'
          filename: xt/author/00-compile.t
          module_finder:
            - ':InstallModules'
          needs_display: '0'
          phase: develop
          script_finder:
            - ':ExecFiles'
          skips: []
      name: '@INGY/Test::Compile'
      version: '2.045'
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@INGY/ReportVersions::Tiny'
      version: '1.10'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@INGY/TestMoreWithSubtests'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@INGY/GithubMeta'
      version: '0.46'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@INGY/@Git/Check'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
          time_zone: local
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@INGY/@Git/Commit'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          signed: 0
          tag: '0.39'
          tag_format: '%v'
          tag_message: v%v
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@INGY/@Git/Tag'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - 'origin :'
          remotes_must_exist: 0
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@INGY/@Git/Push'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::ChangesFromYaml
      name: ChangesFromYaml
      version: '0.004'
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: GithubMeta
      version: '0.46'
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: ExtraTests
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: RunExtraTests
      version: '0.022'
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      config:
        Dist::Zilla::Plugin::Test::NoTabs:
          filename: xt/release/no-tabs.t
          finder:
            - ':InstallModules'
            - ':ExecFiles'
            - ':TestFiles'
      name: NoTabsTests
      version: '0.09'
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: EOLTests
      version: '0.02'
    -
      class: Dist::Zilla::Plugin::Test::Version
      name: Test::Version
      version: '0.002004'
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: MetaTests
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::CheckMetaResources
      name: CheckMetaResources
      version: '0.001'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: recommends
      name: Recommends
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Test::PodSpelling
      name: Test::PodSpelling
      version: '2.006008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.019'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.019'
