
BEGIN {
  unless ($ENV{AUTHOR_TESTING}) {
    require Test::More;
    Test::More::plan(skip_all => 'these tests are for testing by the author');
  }
}

use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006001
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Alessandro
Embeddable
Krotkine
Ranellucci
Walde
priodev
PPI
al
embeddable
et
inlines
irc
optimizations
rw
stevan
suboptimal
ungolfed
versa
Finalizer
getter
ro
instantiation
chainable
API
CPAN
d√∂t
GitHub
mst
OO
runtime
startup
Ingy
d√
Net
ingy
lib
Mo
Golf
Features
import
default
is
exports
build
Design
required
Moose
importer
Hacking
chain
nonlazy
builder
Mouse
coerce
xs
option
exporter
Inline
